src/control/LanguageBean.java
package control;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
 
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

import utils.Utils;
 
@ManagedBean(name="languageBean")
@SessionScoped
public class LanguageBean implements Serializable{
	 
	private static final long serialVersionUID = 1L;
	
	private String localeString;
	private Locale locale = Locale.ENGLISH;
	private Locale localees = new Locale("SPANISH");
 
	public LanguageBean(){
		locale = FacesContext.getCurrentInstance()
    			.getViewRoot().getLocale();

		//loop country map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {

    		// Utils.log("locale : " + locale.toString() + "  map entry: " + entry.getValue().toString());

        	if(entry.getValue().equals(locale)){
        		localeString = entry.getKey();
        		Utils.log("match, localeCode -> " + localeString);
        	}
        }
	}
	
	private static Map<String,Object> countries;
	static{
		countries = new LinkedHashMap<String,Object>();
		countries.put("English", Locale.ENGLISH); //label, value

		countries.put("Spanish", Locale.FRENCH);

		countries.put("German",  Locale.GERMAN);

	}
 
	public Map<String, Object> getCountriesInMap() {
		return countries;
	}
 
 
	public String getLocaleString() {
		return localeString;
	}
 
 
	public void setLocaleString(String localeString) {
		this.localeString = localeString;
	}
 
	public Locale getLocale() {
		return locale;
	}

	public void setLocale(Locale locale) {
		this.locale = locale;
	}


	//value change event listener
	public void countryLocaleCodeChanged(ValueChangeEvent e){
 
		String newLocaleValue = e.getNewValue().toString();
		
		Utils.log("language -> " + newLocaleValue);
		
		//loop country map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {
 
        	if(entry.getValue().toString().equals(newLocaleValue)){
 
        		FacesContext.getCurrentInstance()
        			.getViewRoot().setLocale((Locale)entry.getValue());
        		
        		locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
        		localeString = entry.getKey();
        		Utils.log("localeString -> " + localeString);
        	}
        }
	}
}

src/control/LoginBean.java
package control;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;

import model.User;
import model.UserException;
import model.UserManager;
import utils.Utils;
 
@ManagedBean(name="loginBean")
@SessionScoped
public class LoginBean implements Serializable {
	
	private String name;
	private String password;
	private String welcome = null;
	private boolean submissionSelected = false;
	
	private User user;
	
	@ManagedProperty(value="#{userManager}")
	private UserManager myUserManager;

	public String login (){
		
		try {
			user = myUserManager.login(name, password);
	
			if(user != null) 
			{
				return navigateToApproppriatePage();
			}
		}
		catch(UserException e) {
			FacesContext context = FacesContext.getCurrentInstance();
						
            String errorMsg = Utils.getResourceText(context, "msgs", "invalidUserAndOrPassword");
            FacesMessage msg = new FacesMessage(errorMsg);
            context.addMessage("formLogin:buttonLogin", msg);
			return "login.xhtml";
		}
		return "login.xhtml";
	}


	public String navigateToApproppriatePage() 
	{
		if(this.submissionSelected == false)
		{
			return "frontpageLoggedIn.xhtml";
		}
		else
		{
			return "detailViewLoggedIn.xhtml";
		}
	}
	

	public void checkLogin (FacesContext context, UIComponent component, Object value) {
		
        String nickName = (String)value;

        if (myUserManager.checkIfFree(nickName)){
            ((UIInput)component).setValid(false);
            String errorMsg = Utils.getResourceText(context, "msgs", "userDoesNotExist");
            FacesMessage msg = new FacesMessage(errorMsg);
            context.addMessage(component.getClientId(context), msg);
       	
        }
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public UserManager getMyUserManager() {
		return myUserManager;
	}

	public void setMyUserManager(UserManager myUserManager) {
		this.myUserManager = myUserManager;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		if (user != null){
			Utils.log("setUser: user -> " + user.getLogin() );
		}
		this.user = user;
	}

	public String getLoginName() {
		if (user != null) {
			Utils.log("getLoginName: user = " + user.getLogin() );
			return user.getLogin();
		}
		else{
			return null;
		}
	}
	public void submissionIsSelected (boolean submissionSelected)
	{
		this.submissionSelected = submissionSelected;
	}
}

src/control/RegisterBean.java
package control;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;

import model.User;
import model.UserException;
import model.UserManager;
import utils.Utils;

@ManagedBean(name="registerBean")
@RequestScoped
public class RegisterBean {

	protected String login;
	protected String password;
	protected String password2;
	protected String name;
	protected String mail;
	
	@ManagedProperty(value="#{userManager}")
	private UserManager myUserManager;
	@ManagedProperty(value="#{loginBean}")
	private LoginBean myLogin;
	
	public String register (){
		
		User user = new User();
		user.setLogin(login);
		user.setPassword(password);
		try {
			myUserManager.register(user);
		} catch(UserException e) {
			return "register.xhtml";
		}

		myLogin.setUser(user);

		return myLogin.navigateToApproppriatePage();
	}
	
	
	public void validateNickName (FacesContext context, UIComponent component, Object value) {
		
        String nickName = (String)value;
        
        Utils.log("Validate nick name " + nickName);

        if (! myUserManager.checkIfFree(nickName)){
            ((UIInput)component).setValid(false);
			String errorMsg = Utils.getResourceText(context, "msgs", "userAlreadyExists");
            FacesMessage msg = new FacesMessage(errorMsg);
            context.addMessage(component.getClientId(context), msg);
       	
        }
	}
	
	public String getLogin() {
		return login;
	}
	public void setLogin(String login) {
		this.login = login;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPassword2() {
		return password2;
	}
	public void setPassword2(String password2) {
		this.password2 = password2;
	}
	public void setMyUserManager(UserManager myUserManager) {
		this.myUserManager = myUserManager;
	}
	public void setMyLogin(LoginBean myLogin) {
		this.myLogin = myLogin;
	}
}

src/control/SubmissionBean.java
package control;

import java.io.Serializable;
import java.util.Map;


import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import model.Submission;
import model.Comment;
import model.SubmissionManager;
import model.User;

import org.primefaces.context.RequestContext;

import utils.Utils;
import utils.VoteType;

@ManagedBean(name="submissionBean")
@RequestScoped
public class SubmissionBean implements Serializable {
	
	private String message;
	private Submission selectedSubmission;
	
	@ManagedProperty(value="#{loginBean}")
	private LoginBean myLogin;

	@ManagedProperty(value="#{frontpageBean}")
	private FrontpageBean myFrontpage;
	
	public String addCommentEntry(){
		
		selectedSubmission = myFrontpage.getSelectedSubmission();
		Comment newComment = new Comment(message, myLogin.getLoginName(), selectedSubmission);
		selectedSubmission.addComment(newComment);
		return "detailViewLoggedIn.xhtml";
	}
	
	public int getSubmissionVoteCount()
	{
		selectedSubmission = myFrontpage.getSelectedSubmission();
		return selectedSubmission.getSubmissionVoteCount();
	}
	public String getSubmissionTimestamp()
	{
		selectedSubmission = myFrontpage.getSelectedSubmission();
		return selectedSubmission.getSubmissionTimestamp();
	}
	public String getSubmissionAuthor()
	{
		selectedSubmission = myFrontpage.getSelectedSubmission();
		return selectedSubmission.getSubmissionAuthor();
	}
	public String getSubmissionTitle()
	{
		selectedSubmission = myFrontpage.getSelectedSubmission();
		return selectedSubmission.getSubmissionTitle();
	}
	public String getSubmissionLinkString()
	{
		selectedSubmission = myFrontpage.getSelectedSubmission();
		return selectedSubmission.getSubmissionLinkString();
	}
	public void upVoteSubmission()
	{
		myFrontpage.upVoteSubmission();
	}
	public void downVoteSubmission()
	{
		myFrontpage.downVoteSubmission();
	}
	public void findCommentAndUpvote()
	{
		FacesContext context = FacesContext.getCurrentInstance();
		Map map = context.getExternalContext().getRequestParameterMap();
		String selectedCommentIdString = (String) map.get("commentId");
		int selectedCommentId = Integer.parseInt(selectedCommentIdString);
		myFrontpage.upVoteComment(selectedCommentId);
	}
	public void findCommentAndDownvote()
	{
		FacesContext context = FacesContext.getCurrentInstance();
		Map map = context.getExternalContext().getRequestParameterMap();
		String selectedCommentIdString = (String) map.get("commentId");
		int selectedCommentId = Integer.parseInt(selectedCommentIdString);
		myFrontpage.downVoteComment(selectedCommentId);	}
	

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public void setMyFrontpage(FrontpageBean myFrontpage) {
		this.myFrontpage = myFrontpage;
	}

	public Submission getSelectedSubmission() {
		return  this.myFrontpage.getSelectedSubmission();
	}

	public void setMyLogin(LoginBean myLogin) {
		this.myLogin = myLogin;
	}	
	public String leaveSubmission()
	{
		myFrontpage.resetSelectedSubmission();		
		if(myLogin.getLoginName() == null)
		{
			return "frontpageLoggedOut.xhtml";
		}
		else
		{
			return "frontpageLoggedIn.xhtml";
		}
	}
}

WebContent/detailViewLoggedIn.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:p="http://primefaces.org/ui">
<h:head>
<style type="text/css">


      html { 
  background: url(images/reddit_logo8.jpg) no-repeat fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
       
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #c1ed9c;
	-webkit-box-shadow:inset 0px 1px 0px 0px #c1ed9c;
	box-shadow:inset 0px 1px 0px 0px #c1ed9c;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #9dce2c), color-stop(1, #8cb82b) );
	background:-moz-linear-gradient( center top, #9dce2c 5%, #8cb82b 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#9dce2c', endColorstr='#8cb82b');
	background-color:#9dce2c;
	-webkit-border-top-left-radius:15px;
	-moz-border-radius-topleft:15px;
	border-top-left-radius:15px;
	-webkit-border-top-right-radius:15px;
	-moz-border-radius-topright:15px;
	border-top-right-radius:15px;
	-webkit-border-bottom-right-radius:0px;
	-moz-border-radius-bottomright:0px;
	border-bottom-right-radius:0px;
	-webkit-border-bottom-left-radius:0px;
	-moz-border-radius-bottomleft:0px;
	border-bottom-left-radius:0px;
	text-indent:0;
	border:1px solid #83c41a;
	display:inline-block;
	color:#ffffff;
	font-family:Georgia;
	font-size:15px;
	font-weight:bold;
	font-style:normal;
	height:40px;
	line-height:40px;
	width:86px;
	text-decoration:none;
	text-align:center;
	text-shadow:1px 1px 0px #689324;
}
.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #8cb82b), color-stop(1, #9dce2c) );
	background:-moz-linear-gradient( center top, #8cb82b 5%, #9dce2c 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#8cb82b', endColorstr='#9dce2c');
	background-color:#8cb82b;
}.classname:active {
	position:relative;
	top:1px;
}


.updawn{
width: 0px;
height: 0px;
border-style: solid;
border-width: 0 20px 40px 20px;
border-color: transparent transparent #007bff transparent;
line-height: 0px;
_border-color: #000000 #000000 #007bff #000000;
_filter: progid:DXImageTransform.Microsoft.Chroma(color='#000000');
}

</style>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><h:outputText value="#{msgs.title}"></h:outputText></title>

</h:head>

<h:body style="width: 1218px; ">
	<f:view locale="#{languageBean.locale}">
    <h:form>
    <h2>
    <h:outputText value="#{msgs.greeting} "></h:outputText><h:outputText value="#{loginBean.loginName} "></h:outputText><h:outputText value="#{msgs.title}"></h:outputText>
    <h:outputText value="    "></h:outputText>
    
    <h:outputText value=" "></h:outputText>
    <h:commandButton class="classname" value="#{msgs.logoutButton}" action="#{frontpageBean.logout}" style="width: 169px; "></h:commandButton>
    <h:outputText value=" "></h:outputText>
    
    </h2>
	</h:form>
	<h:form>
	<h2>
	<h:outputText value="#{submissionBean.submissionVoteCount}   " style="font-size: 12px; font-family: Verdana, Arial, Sans-Serif; border-top-style: none "></h:outputText>
	<p:button href="#{submissionBean.submissionLinkString}" value="#{submissionBean.submissionTitle}" />
	<br/>
	</h2>
	</h:form>
	<h4>
	<h:form>
	<h:commandButton class="classname" value="#{msgs.voteUp}" action="#{submissionBean.upVoteSubmission}" style="width: 134px; "></h:commandButton>-<h:commandButton class="classname" value="#{msgs.voteDown}" action="#{submissionBean.downVoteSubmission}" style="width: 148px; "></h:commandButton>
	</h:form>
	<br/>
	<h:outputText value=" #{msgs.submitted} " style="color: #FF0000"></h:outputText>
	<h:outputText value="#{submissionBean.submissionTimestamp} " style="color: #FF0000"></h:outputText>
	<h:outputText value=" #{msgs.submitter} " style="color: #FF0000"></h:outputText> 
	<h:outputText value="#{submissionBean.submissionAuthor}" style="color: #0080FF; text-decoration: underline"></h:outputText>
	<br/>	
	<h:form id="newCommentForm">
		<h:panelGrid border="0" columns="2" style="width: 799px; ">
			<h:inputText id="newComment" value="#{submissionBean.message}" required="true" size="80">
			</h:inputText>
			<h:commandButton class="classname" value="#{msgs.sendButton}" action="#{submissionBean.addCommentEntry}" style="width: 129px; ">
			</h:commandButton>
		</h:panelGrid>
		<h6>
			
   		</h6>
	</h:form>


	<h:form>
		<h:commandButton class="classname" value="#{msgs.backToFrontpage}" action="#{submissionBean.leaveSubmission}" style="width: 236px; ">
		</h:commandButton>
	</h:form>
	
	</h4>
	<h6>
	<h:form style="width: 1200px; ">	
		<p:panel style="background-image:url(images/abstract5.jpg);" id="submissionDataPanel" header="#{submissionBean.selectedSubmission.amountOfComments} #{msgs.commentLogs}">
			<c:forEach items="#{submissionBean.selectedSubmission.submissionComments}" var="item">
				
				
				<h1>________________________________________________________________________</h1><h:outputText value="#{item.commentContent}" style="font-size: 16px; color: #FFFFFF"></h:outputText><br/>
				<h:outputText value="#{item.commentAuthor} " style="color: #0080FF; text-decoration: underline blink"></h:outputText>
				<h:outputText value="#{item.commentTimestamp}" style="color: #FF0000"></h:outputText>
				<br/>
			<i>	 </i>
				<br /><h:outputText value="#{item.commentVoteCount}  " style="color: #FFFFFF"></h:outputText><h:commandButton class="classname" value="#{msgs.voteUp}" action="#{submissionBean.findCommentAndUpvote}" style="width: 137px; ">
				<f:param name="commentId" value="#{item.commentId}" />
				</h:commandButton>-<h:commandButton class="classname" value="#{msgs.voteDown}" action="#{submissionBean.findCommentAndDownvote}" style="width: 129px; ">
				<f:param name="commentId" value="#{item.commentId}" />
				</h:commandButton><br/>
			</c:forEach>
		</p:panel>
		<p:poll interval="3" update="submissionDataPanel" widgetVar="poll" autoStart="true"
		 listener="#{submissionBean.selectedSubmission.pollListener}"></p:poll>  
	</h:form>
	</h6>

	</f:view>	
</h:body>
</html>

WebContent/frontpageLoggedIn.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:c="http://java.sun.com/jsp/jstl/core"
		xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets" >
      
<h:head>
   
	<style type="text/css">
	
	      html { 
  background: url(images/reddit_logo8.jpg) no-repeat fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
	
	.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #c1ed9c;
	-webkit-box-shadow:inset 0px 1px 0px 0px #c1ed9c;
	box-shadow:inset 0px 1px 0px 0px #c1ed9c;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #9dce2c), color-stop(1, #8cb82b) );
	background:-moz-linear-gradient( center top, #9dce2c 5%, #8cb82b 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#9dce2c', endColorstr='#8cb82b');
	background-color:#9dce2c;
	-webkit-border-top-left-radius:15px;
	-moz-border-radius-topleft:15px;
	border-top-left-radius:15px;
	-webkit-border-top-right-radius:15px;
	-moz-border-radius-topright:15px;
	border-top-right-radius:15px;
	-webkit-border-bottom-right-radius:0px;
	-moz-border-radius-bottomright:0px;
	border-bottom-right-radius:0px;
	-webkit-border-bottom-left-radius:0px;
	-moz-border-radius-bottomleft:0px;
	border-bottom-left-radius:0px;
	text-indent:0;
	border:1px solid #83c41a;
	display:inline-block;
	color:#ffffff;
	font-family:Georgia;
	font-size:15px;
	font-weight:bold;
	font-style:normal;
	height:40px;
	line-height:40px;
	width:86px;
	text-decoration:none;
	text-align:center;
	text-shadow:1px 1px 0px #689324;
}
.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #8cb82b), color-stop(1, #9dce2c) );
	background:-moz-linear-gradient( center top, #8cb82b 5%, #9dce2c 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#8cb82b', endColorstr='#9dce2c');
	background-color:#8cb82b;
}.classname:active {
	position:relative;
	top:1px;
}



</style>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>
         <h:outputText value="#{msgs.title}">
         </h:outputText>
      </title>
   </h:head>
   <h:body>
   
      <f:view locale="#{languageBean.locale}">
      <h2>
         <p:panel style=" background-image:url(images/abstract2.jpg); width: 480px;" id="frontpagePanel">

            <h:form>
            	<h:outputText value= " #{msgs.greeting}  " style="font-size: 24px; color: #FFFFFF"> </h:outputText>    <h:outputText value= " #{loginBean.loginName} " style="font-size: 24px; color: #FFFFFF"> </h:outputText> <h:commandButton href="#" class="classname" value="#{msgs.logoutButton}" action="#{frontpageBean.logout}" style="width: 220px; font-size: 16px"></h:commandButton><br /><br /><h:outputText value="#{msgs.title}     " style="font-size: 24px; color: #FFFFFF">        </h:outputText>               
            	    <h:commandButton href="#" class="classname" value=" #{msgs.submitLinkButton}" action="submitLink.xhtml" style="width: 231px; font-size: 16px; "></h:commandButton><br /><h:outputText value=""></h:outputText>
      			<br />
      			
            </h:form>
         </p:panel>
      </h2>
      <h4>
		<h:form style="width: 1200px;   ">	
			<p:panel style="background-image:url(images/abstract5.jpg);" id="allSubmissionsPanel">
				<c:forEach items="#{submissionManager.submissionsVector}" var="item">
					<h:outputText value="#{item.submissionVoteCount}   " style="color: #FFFFFF"></h:outputText>
					<p:button href="#{item.submissionLinkString}" value="#{item.submissionTitle}" />
					<br/>
					<h:commandButton href="#" class="classname" value="#{msgs.voteUp}" action="#{frontpageBean.findSubmissionAndUpvote}" style="width: 169px; ">
					<f:param name="title" value="#{item.submissionTitle}" /> 
					</h:commandButton>-<h:commandButton href="#" class="classname" value="#{msgs.voteDown}" action="#{frontpageBean.findSubmissionAndDownvote}" style="width: 167px; ">
					<f:param name="title" value="#{item.submissionTitle}" /> 
					</h:commandButton>
					<br/>
					<h:outputText value=" #{msgs.submitted} " style="color: #FFFFFF"></h:outputText>
					<h:outputText value="#{item.submissionTimestamp} " style="color: #FFFFFF"></h:outputText>
					<h:outputText value=" #{msgs.submitter} " style="color: #FFFFFF"></h:outputText> 
					<h:outputText value="#{item.submissionAuthor}" style="color: #FFFFFF"></h:outputText>
					<br/>
					<h:commandButton href="#" class="classname" value="#{item.amountOfComments} #{msgs.comments}" action="#{frontpageBean.openDetailViewPage}" style="width: 184px; ">
					<f:param name="title" value="#{item.submissionTitle}" /> 
					</h:commandButton>
					 <p>________________________________________________________________________________________________</p>
           
					
				</c:forEach>
			</p:panel>
			<p:poll interval="3" update="allSubmissionsPanel" widgetVar="poll" autoStart="true"></p:poll>  
		</h:form>
	 </h4>

      </f:view>
   </h:body>
</html>